-- insertar un nuevo registro en el PUBLICADOR
insert [LAPTOP-P59U9Q17\INSTANCIANORTH].MUEBLETEC2.dbo.[VENTA] (SUCID, CLAVEVENTA, IMPORTE, CLAVECLI, TIPOVENTA, FECHA)
values(100, 401, 5555, 2, 'CONTADO','2020-07-16' ) 

insert [LAPTOP-P59U9Q17\INSTANCIANORTH].MUEBLETEC2.dbo.[DETAILVENTA] (SUCID, CLAVEVENTA, CLAVEART, CANTIDAD, IMPORTE)
values(100, 401, 1, 3, 1350) 

-- verificar en el SUSCRIPTOR
select * from [DESKTOP-BT5BO9U\SQLSERVER].MUEBLETEC2.dbo.[venta] where sucid = 100 and claveventa = 401
select * from [DESKTOP-BT5BO9U\SQLSERVER].MUEBLETEC2.dbo.[detailventa] where sucid = 100 and claveventa = 401

----> SCRIPT DE SUSCRIPTOR
insert [DESKTOP-BT5BO9U\SQLSERVER].MUEBLETEC2.dbo.[VENTA] ( SUCID,CLAVEVENTA,IMPORTE,CLAVECLI,TIPOVENTA,FECHA)
VALUES 
(100,13,5000,4,'CONTADO',GETDATE()) 

insert [DESKTOP-BT5BO9U\SQLSERVER].MUEBLETEC2.dbo.[DETAILVENTA] (SUCID,CLAVEVENTA,CLAVEART,CANTIDAD,IMPORTE)
values
(100, 13, 5,10,10000 )  

-- verificar en el distribuidor
select * from [LAPTOP-P59U9Q17\INSTANCIANORTH].MUEBLETEC2.dbo.VENTA where sucid = 100 and claveventa = 13
select * from [LAPTOP-P59U9Q17\INSTANCIANORTH].MUEBLETEC2.dbo.DETAILVENTA where sucid = 100 and claveventa = 13

-->ELIMINAR ALGUN REGISTRO
DELETE DETAILVENTA WHERE CLAVEVENTA = 400
DELETE VENTA WHERE CLAVEVENTA = 400

